### ISSUE TITLE
can you release your datasets for testing

### ISSUE THREAD

**Issue by puallee** [YeongHyeon/LungCT_Super_Resolution#3]
Thanks for your nice work， can you release your datasets for testing？

**Comment by YeongHyeon** [comment]
you can find lung CT dataset by web searching easily.

**Comment by puallee** [comment]
Thanks for your kind reply. Can you give me a links or name of datasets&nbsp;





------------------ Original ------------------
From: YeongHyeon Park ***@***.***&gt;
Date: Mon,Mar 28,2022 1:32 PM
To: YeongHyeon/LungCT_Super_Resolution ***@***.***&gt;
Cc: Pual ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [YeongHyeon/LungCT_Super_Resolution] can you release your datasets for testing (Issue #3)





 
you can find lung CT dataset by web searching easily.
